import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-bgimg bg-fixed`}>
        <Navbar />
        <div className='flex w-full justify-center'>
          <div className='promotion  mt-10 h-[1500px]'>{children}</div>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
