import GameCard from '@/components/GameCard'
import { GAMES } from '@/utils/games'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div
      className='
          grid
          lg:grid-cols-3
          md:grid-cols-2
          sm:grid-cols-2
          xl:grid-cols-3
          2xl:grid-cols-3
          py-4
          gap-4
          justify-items-center justify-center items-center content-center z-[1]'
    >
      {GAMES.map((game) => (
        <GameCard
          key={game.id}
          img={game.img}
          logo={game.logo}
          color={game.color}
          title={game.title}
          desc={game.desc}
          hours={game.hours}
          minutes={game.minutes}
          percent={game.percent}
          multiplier={game.multiplier}
        />
      ))}
    </div>
  )
}
