import BonusTime from '@/components/BonusTime'
import { BONUS_TIME } from '@/utils/bonustimes'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Bonus time',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <div
      className='
          grid 2xl:grid-cols-3 items-center justify-items-center gap-16 py-8 xs:grid-cols-1 px-0 2xl:pr-6 2xl:pb-12'
    >
      {BONUS_TIME.map((v) => (
        <BonusTime
          key={v.id}
          game={v.game}
          start={v.start}
          end={v.end}
          hours={v.hours}
          minutes={v.minutes}
        />
      ))}
    </div>
  )
}

export default Page
